"""create ticket history table

Revision ID: 28fe405385ab
Revises: b410431324a5
Create Date: 2026-07-13 14:10:13.541729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fe405385ab'
down_revision: Union[str, Sequence[str], None] = 'b410431324a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('created', 'assigned', 'unassigned', 'status_changed', 'priority_changed', name='ticket_history_action'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_history_action'), 'ticket_history', ['action'], unique=False)
    op.create_index(op.f('ix_ticket_history_actor_id'), 'ticket_history', ['actor_id'], unique=False)
    op.create_index(op.f('ix_ticket_history_ticket_id'), 'ticket_history', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_history_ticket_id'), table_name='ticket_history')
    op.drop_index(op.f('ix_ticket_history_actor_id'), table_name='ticket_history')
    op.drop_index(op.f('ix_ticket_history_action'), table_name='ticket_history')
    op.drop_table('ticket_history')
    # ### end Alembic commands ###
